### ISSUE TITLE
VPN Blocks 6868 and 25555

### ISSUE THREAD

**Issue by hhercules** [pivotal-cf-experimental/bosh-bootloader#18]
Although this is not a bbl issue wanted to call it out. Right now having to do bosh on AWS work outside of VPN, and when that is done, I can connect back to VPN. I have made the request to get those open, but is a challenge because of the wide range of IP's for AWS. 

I may have started command while off vpn and then jumped onto VPN. 

Cleaning up rendered CPI jobs... Finished (00:00:00)

Command 'deploy' failed:
  Deploying:
    Creating instance 'bosh/0':
      Waiting until instance is ready:
        Sending ping to the agent:
          Performing request to agent endpoint 'https://mbus-user-WZAZmbBXHfqLb9h:mbus-LNQelrVFOGVU5Dr@XXX.XXX.XXX.XXX:6868/agent':
            Performing POST request:
              Post https://mbus-user-WZAZmbBXHfqLb9h:mbus-LNQelrVFOGVU5Dr@XXX.XXX.XXX.XXX:6868/agent: dial tcp XXX.XXX.XXX.XXX:6868: getsockopt: connection refused

**Comment by Amit-PivotalLabs** [comment]
Hey @hhercules 

Thanks.  So sounds like you were off VPN, started doing some `bbl` stuff, reconnected to VPN, and that broke your connection to the IP in AWS, causing the connection between local `bbl` (and underlying BOSH client) to lose connection to the BOSH VM, is that correct?  Were you able to recover from this scenario?

Please note we have an upcoming track to make `bbl` command re-entrant, so that you should be able to re-run a command that fails midway and it will pick up where it left off: https://www.pivotaltracker.com/epic/show/2401727

For the time being I don't believe there's much more `bbl` can do about this, so I'll go ahead and close this issue.

Best,
Amit
