### ISSUE TITLE
Optionally tag infrastructure components

### ISSUE THREAD

**Issue by robdimsdale** [pivotal-cf-experimental/bosh-bootloader#30]
When using `bbl` to create multiple VPCs etc on the same account, it is hard to differentiate which components belong to which `state.json`.

For example, all the VPCs are named `bbl` and the subnets are `Internal1`, `LoadBalancer2` etc.

If `bbl` supported an optional `--tag` we could prepend/append this tag to aid discovery, e.g. `VPC-my-tag` or `IAAS-3-Loadbalancer2`.

I haven't made an exhaustive list of the components this tag should be added to, but I imagine this would apply to more than just VPC and subnets.

Thanks,
Rob

**Comment by Amit-PivotalLabs** [comment]
Many people have requested some variation of this, so I'd like to get some input on what people want.  The minimal thing I can think of is that `bbl` generates a random name the first time you create the environment, and it tags every resource it can with key `bbl-tag` and value being whatever name that is.  This random name could start with something human readable, so e.g. `rabbit-df78s8dfff`.

Once we start to get into multiple tags, user-provided tags, changing tags, adding tags, removing tags, etc. everything becomes much more complex, and not something I want to even consider right now as it will distract from building an MVP that people can use.  I'd like to know:

**Does the proposal (single, immutable, non-configurable tag) above help solve a major concern you have with using `bbl`? Is it missing any other major considerations?**

It'll be helpful to keep in mind that `bbl` is not meant to be the enterprise-grade solution to bootstrap and manage complex, mission-critical production environments.  It's meant to greatly ease the getting-started experience with BOSH, especially for Concourse and CF, and to be a good tool for managing non-snowflake BOSH environments for CI purposes, especially CI for projects that are core-contributors to the CF/BOSH ecosystem.

Input would be greatly appreciated.

/cc @SocalNick @robdimsdale @zankich @ryanmoran @zachgersh @mavenraven @hhercules @dsabeti

**Comment by robdimsdale** [comment]
If the `bbl` user cannot choose this string, how will they correlate that with the Cloudformation stack, and everything in it?

If I have multiple `bbl`'d environments, how I will i know that `rabbit` means "my env 1" and `other-random-human-readable-string`? Maybe I can use `bbl` on a local workstation to map these two pieces of information, but that seems like an unnecessary amount of effort.

It would be a lot easier for the user if they can choose the string. I can't image that's a significant amount more work for `bbl`?

**Comment by Amit-PivotalLabs** [comment]
The idea would be that the stack, and everything in it, is tagged with the generated string.  AWS has built in notion of tagging for most resources.  There could be a `bbl` command which tells you the `bbl-tag` value for a given `--state-dir`.

If it's user provided, is it optional? Is it mutable? How should idempotence be handled if the user runs `up` twice with a different tag/name?  These questions are answerable, but is it necessary to solve the problem you're trying to solve?

**Comment by robdimsdale** [comment]
Sure, and most of those questions could be applied to whomever is generating the string. The fact that `bbl` generates the string just answers them with "you cannot change it". We could take the same logic and apply it to the user-provided string.

- optional: yes
- mutable: no
- runs `up` with different tag/name: fail-fast with error message

**Comment by hhercules** [comment]
What I would be looking for really is since bbl creates a stack and ec2 instances for bbl to pass along tag key/value pair to http://docs.aws.amazon.com/sdk-for-go/api/service/cloudformation.html#type-Tag  and http://docs.aws.amazon.com/sdk-for-go/api/service/ec2/EC2.html#CreateTags-instance_method while creating stack/ec2 instance. If you would run again, it could get updated if you wanted. 

Seems there is some bosh manifest support for some tagging, but need to look at this further. 
https://github.com/cloudfoundry/bosh/issues/890

I know you are not trying to create tool for enterprise, but for AWS at least tagging is important in helping distinguish who created resources and what they are for. The way I see it you would just be passing along extra parameters to calls you are already making.

**Comment by ryanmoran** [comment]
In truth, I really don't care about changing this value, or having it even be something human-friendly. My main purpose was to be able to quickly see from the AWS console that a BOSH director or ELB was connected to a certain bbl environment. For me, tagging everything that bbl creates with the stack name would serve this purpose well.

**Comment by zankich** [comment]
Using the stack name would be a nice default value, that way there is a clear connection all the way through. Maybe instead of allowing an optional tag name, we allow for an optional stack name, and always tag everything with your stack name.

**Comment by ryanmoran** [comment]
Having the option to name the stack is another feature I would be interested in. When you have 2 or 3 bbl environments, it can be hard to know which one is being used for what purpose. But tagging the instances with the randomized stack name is a good start.

**Comment by SocalNick** [comment]
+1 for being able to specify a "name" when I `bbl up` and using that to tag everything the stack creates. No need to support changing it.

**Comment by Amit-PivotalLabs** [comment]
https://github.com/pivotal-cf-experimental/bosh-bootloader/issues/38

**Comment by Amit-PivotalLabs** [comment]
We should make it so that bbl applies some sort of consistent tag(s) across all AWS resources it creates, and also use this in the BOSH Director name.  It would be helpful to better understand **why** folks want to do the tagging.  It seems like a reasonable request, but understanding all the goals will help us figure out what the best UX for this is.

Ryan mentioned that it would help distinguishing the **purpose** of an environment.  In addition to that, Brando mentioned that it would help know **who created** the environment.  Out of band, he's also mentioned having an **email contact** and **project name** in the tags, among other things.

How does the following proposal sound?:

* `bbl` creates a human-readable random id the first time an environment is bbl'd up, and applies it to everything.  This cannot be chosen by the user or changed.  It will tag all AWS resources created with the key `bbl-env-id` and the BOSH director should be named `bosh-${BBL_ENV_ID}`.

* `bbl env-id` can be used to get the value.  It is read-only.

* `bbl` can support `env-description`, `set-env-description DESCRIPTION`, and `delete-env-description` for managing the value of a `bbl-env-description` tag across all AWS resources `bbl` manages.  This allows all CRUD operations (create and update are the same operation).

* rather than bloat the responsibilities and UX of `bbl`, additional tagging can be implemented out of band, by using the AWS CLI to fetch all resources with the `bbl env-id` tag, and then adding any other desired additional tags.

**Comment by ryanmoran** [comment]
This proposal works for me.

**Comment by Amit-PivotalLabs** [comment]
We've created an [epic](https://www.pivotaltracker.com/epic/show/2573117) to support tagging.  I will close out this issue for now, but feedback on the stories in that epic is still welcome.

**Comment by actdiux** [comment]
Was anything like this ever implemented?
