### ISSUE TITLE
bbl should have a command to obtain the director ip address alone

### ISSUE THREAD

**Issue by APShirley** [pivotal-cf-experimental/bosh-bootloader#43]
Currently to ssh we need to do the following to pass in the gateway host
`bosh ssh --gateway_host $(bbl director-address | sed 's/https:\/\///' | sed 's/:25555//')`

**Comment by Amit-PivotalLabs** [comment]
@zankich @ryanmoran @robdimsdale can you think of any reason why to not simply replace `director-address` with `director-ip`?  We don't allow bbl users to change the protocol and port, and BOSH by default prepends https and appends :25555 during `bosh target`, so for `bosh target` and `bosh ssh --gateway_host`, the IP should be sufficient.

**Comment by ryanmoran** [comment]
@Amit-PivotalLabs we've already written some code that relies upon the full url, but it wouldn't be too much of a pain to change. Maybe provide both for some short period of time, with `director-address` spitting out a deprecation warning on stderr?

**Comment by Amit-PivotalLabs** [comment]
Just spoke to @cppforlife, turns out there's an even nicer solution: http://bosh.io/jobs/director?source=github.com/cloudfoundry/bosh&version=257.1#p=director.default_ssh_options.gateway_host

Never need to pass `--gateway_host` (or `--gateway_user`) again!  Think we'll do this, and punt on `director-address` vs `director-ip` for now.

Created this story: https://www.pivotaltracker.com/story/show/123648261

Closing.
